name: Deploy node application

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t tiru2167/nodejs-app .
      - name: Publish Image to docker hub
        run: docker push tiru2167/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull tiru2167/nodejs-app
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name nodejs-app-container-new tiru2167/nodejs-app